# TOML file

[terminal]
shell = "/bin/zsh"

[window]
opacity = 0.9
decorations = "full"

padding = { x = 5, y = 5 }

[font]
size = 11.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xc0caf5"

[colors.cursor]
text = "0x1e1e2e"
cursor = "0x9d7cd8"

[colors.selection]
text = "0x1e1e2e"
background = "0x9d7cd8"

[colors.normal]
black = "0x1e1e2e"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x74c7ec"
magenta = "0xca47e7"
cyan = "0x89dceb"
white = "0xc0caf5"
